#!/bin/bash

set -e

error() {
  echo " ! $1"
}

# Check that we have a Staticfile.auth we can use
echo "Checking Staticfile.auth..."
if [[ ! -f Staticfile.auth ]]; then
  error "You are attempting to deploy to an environment that requires a Staticfile.auth, but do not have one locally."
  error "Please add a Staticfile.auth file to this directory and try again."
  error
  error "For information on generating a Staticfile.auth, see"
  error "http://docs.cloudfoundry.org/buildpacks/staticfile/index.html#basic-auth"
  exit 1
fi
echo "OK!"

bundle exec middleman build
cp Staticfile.auth build
cf target -o govuk-service-manual -s product-pages
cf push
